# Generated by Django 5.0.3 on 2026-04-23 08:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('inventory', '0009_stockcategory_alias_stockgroup_alias'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItemTax',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft-delete flag. Inactive records are hidden by default.')),
                ('sync_status', models.CharField(choices=[('PENDING', 'Pending'), ('SYNCED', 'Synced'), ('FAILED', 'Failed')], db_index=True, default='PENDING', help_text='Status of synchronization with Tally.', max_length=20)),
                ('tally_id', models.CharField(blank=True, db_index=True, help_text='External ID mapping to the Tally record.', max_length=255, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='Timestamp of the last successful synchronization.', null=True)),
                ('hsn_sac_code', models.CharField(blank=True, max_length=20, null=True)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_gst_applicable', models.BooleanField(default=True)),
                ('taxability', models.CharField(choices=[('Taxable', 'Taxable'), ('Exempt', 'Exempt'), ('Nil Rated', 'Nil Rated')], default='Taxable', max_length=20)),
                ('company', models.ForeignKey(help_text='The company this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who created this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tax_data', to='inventory.stockitem')),
                ('updated_by', models.ForeignKey(blank=True, help_text='The user who last updated this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stock Item Tax Detail',
                'verbose_name_plural': 'Stock Item Tax Details',
            },
        ),
    ]
