# Generated by Django 5.0.3 on 2026-04-24 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxation', '0002_gstprofile_hsncode_ledgertaxmapping_taxrate_and_more'),
        ('voucher', '0006_customvouchertype_voucher_custom_voucher_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total Central GST amount for this voucher', max_digits=20)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total State GST amount for this voucher', max_digits=20)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total Integrated GST amount for this voucher', max_digits=20)),
                ('total_tax', models.DecimalField(decimal_places=2, help_text='Sum of all GST components', max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_details', to='voucher.voucher')),
            ],
            options={
                'verbose_name': 'Voucher Tax Detail',
                'verbose_name_plural': 'Voucher Tax Details',
            },
        ),
    ]
