# Generated by Django 5.0.3 on 2026-04-19 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally_integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='synclog',
            name='synced_ids',
            field=models.JSONField(blank=True, default=list, help_text='List of UUIDs for records created or updated in this sync.'),
        ),
    ]
