# Generated by Django 5.0.3 on 2026-04-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally_integration', '0002_synclog_synced_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synclog',
            name='tally_id',
            field=models.CharField(blank=True, db_index=True, help_text='External ID mapping to the Tally record.', max_length=255, null=True),
        ),
    ]
