# Generated by Django 5.0.3 on 2026-04-23 08:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('voucher', '0006_customvouchertype_voucher_custom_voucher_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft-delete flag. Inactive records are hidden by default.')),
                ('sync_status', models.CharField(choices=[('PENDING', 'Pending'), ('SYNCED', 'Synced'), ('FAILED', 'Failed')], db_index=True, default='PENDING', help_text='Status of synchronization with Tally.', max_length=20)),
                ('tally_id', models.CharField(blank=True, db_index=True, help_text='External ID mapping to the Tally record.', max_length=255, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='Timestamp of the last successful synchronization.', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(help_text='The company this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who created this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='The user who last updated this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('voucher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval_data', to='voucher.voucher')),
            ],
            options={
                'verbose_name': 'Voucher Approval',
                'verbose_name_plural': 'Voucher Approvals',
            },
        ),
    ]
