# Generated by Django 5.2.13 on 2026-04-17 12:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('ledger', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft-delete flag. Inactive records are hidden by default.')),
                ('sync_status', models.CharField(choices=[('PENDING', 'Pending'), ('SYNCED', 'Synced'), ('FAILED', 'Failed')], db_index=True, default='PENDING', help_text='Status of synchronization with Tally.', max_length=20)),
                ('tally_id', models.CharField(blank=True, db_index=True, help_text='External ID mapping to the Tally record.', max_length=255, null=True, unique=True)),
                ('number', models.CharField(editable=False, help_text='Auto-generated voucher number (e.g., SAL-0001).', max_length=50)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('voucher_type', models.CharField(choices=[('CONTRA', 'Contra'), ('PAYMENT', 'Payment'), ('RECEIPT', 'Receipt'), ('JOURNAL', 'Journal'), ('SALES', 'Sales'), ('PURCHASE', 'Purchase')], db_index=True, max_length=20)),
                ('narration', models.TextField(blank=True, help_text='General comments for this transaction.')),
                ('company', models.ForeignKey(help_text='The company this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who created this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='The user who last updated this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voucher',
                'verbose_name_plural': 'Vouchers',
                'ordering': ['-date', '-number'],
            },
        ),
        migrations.CreateModel(
            name='VoucherEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft-delete flag. Inactive records are hidden by default.')),
                ('sync_status', models.CharField(choices=[('PENDING', 'Pending'), ('SYNCED', 'Synced'), ('FAILED', 'Failed')], db_index=True, default='PENDING', help_text='Status of synchronization with Tally.', max_length=20)),
                ('tally_id', models.CharField(blank=True, db_index=True, help_text='External ID mapping to the Tally record.', max_length=255, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Absolute value of the transaction.', max_digits=20)),
                ('entry_type', models.CharField(choices=[('DR', 'Debit'), ('CR', 'Credit')], help_text='DR for Debit, CR for Credit.', max_length=2)),
                ('company', models.ForeignKey(help_text='The company this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who created this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voucher_entries', to='ledger.ledger')),
                ('updated_by', models.ForeignKey(blank=True, help_text='The user who last updated this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='voucher.voucher')),
            ],
            options={
                'verbose_name': 'Voucher Entry',
                'verbose_name_plural': 'Voucher Entries',
            },
        ),
        migrations.CreateModel(
            name='VoucherSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_type', models.CharField(choices=[('CONTRA', 'Contra'), ('PAYMENT', 'Payment'), ('RECEIPT', 'Receipt'), ('JOURNAL', 'Journal'), ('SALES', 'Sales'), ('PURCHASE', 'Purchase')], max_length=20)),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['company', 'date', 'voucher_type'], name='voucher_vou_company_35e668_idx'),
        ),
        migrations.AddIndex(
            model_name='voucherentry',
            index=models.Index(fields=['company', 'ledger', 'voucher'], name='voucher_vou_company_67d1e9_idx'),
        ),
        migrations.AddConstraint(
            model_name='voucherentry',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='voucher_entry_amount_positive'),
        ),
        migrations.AlterUniqueTogether(
            name='vouchersequence',
            unique_together={('company', 'voucher_type')},
        ),
    ]
