# Generated by Django 5.2.13 on 2026-04-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='is_posted',
            field=models.BooleanField(db_index=True, default=False, help_text='Once posted, the voucher and its entries become read-only.'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last successful synchronization.', null=True),
        ),
        migrations.AddField(
            model_name='voucherentry',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last successful synchronization.', null=True),
        ),
    ]
