# Generated by Django 5.2.13 on 2026-04-18 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stockitem_last_synced_at_and_more'),
        ('voucher', '0002_voucher_is_posted_voucher_last_synced_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherentry',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Quantity for item-based entries.', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='voucherentry',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rate per unit.', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='voucherentry',
            name='stock_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucher_entries', to='inventory.stockitem'),
        ),
    ]
