# Generated by Django 5.0.3 on 2026-04-21 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0003_voucherentry_quantity_voucherentry_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='party_name',
            field=models.CharField(blank=True, help_text='Name of the associated party (Customer, Vendor, etc.)', max_length=255, null=True),
        ),
    ]
