# Generated by Django 5.0.3 on 2026-04-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0004_voucher_party_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='tally_id',
            field=models.CharField(blank=True, db_index=True, help_text='External ID mapping to the Tally record.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='voucherentry',
            name='tally_id',
            field=models.CharField(blank=True, db_index=True, help_text='External ID mapping to the Tally record.', max_length=255, null=True),
        ),
    ]
