# Generated by Django 5.0.3 on 2026-04-23 06:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('voucher', '0005_alter_voucher_tally_id_alter_voucherentry_tally_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomVoucherType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.')),
                ('sync_status', models.CharField(choices=[('PENDING', 'Pending'), ('SYNCED', 'Synced'), ('FAILED', 'Failed')], db_index=True, default='PENDING', help_text='Status of synchronization with Tally.', max_length=20)),
                ('tally_id', models.CharField(blank=True, db_index=True, help_text='External ID mapping to the Tally record.', max_length=255, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='Timestamp of the last successful synchronization.', null=True)),
                ('name', models.CharField(max_length=255)),
                ('parent_type', models.CharField(choices=[('CONTRA', 'Contra'), ('PAYMENT', 'Payment'), ('RECEIPT', 'Receipt'), ('JOURNAL', 'Journal'), ('SALES', 'Sales'), ('PURCHASE', 'Purchase')], help_text='Base system behavior to inherit (e.g., SALES, PURCHASE).', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('method_of_numbering', models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual'), ('None', 'None')], default='Automatic', max_length=50)),
                ('company', models.ForeignKey(help_text='The company this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who created this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='The user who last updated this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Custom Voucher Type',
                'verbose_name_plural': 'Custom Voucher Types',
                'ordering': ['name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.AddField(
            model_name='voucher',
            name='custom_voucher_type',
            field=models.ForeignKey(blank=True, help_text='Optional link to a user-defined custom voucher type.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers', to='voucher.customvouchertype'),
        ),
    ]
