# Generated by Django 5.0.3 on 2026-04-24 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxation', '0003_vouchertax'),
        ('voucher', '0006_customvouchertype_voucher_custom_voucher_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherentry',
            name='gst_applicable',
            field=models.BooleanField(default=False, help_text='Enable GST calculation for this entry'),
        ),
        migrations.AddField(
            model_name='voucherentry',
            name='hsn_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucher_entries', to='taxation.hsncode'),
        ),
        migrations.AddField(
            model_name='voucherentry',
            name='tax_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='GST percentage applied to this entry', max_digits=5, null=True),
        ),
    ]
