# Generated by Django 5.0.3 on 2026-04-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0007_voucherentry_gst_applicable_voucherentry_hsn_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('APPROVED', 'Approved')], db_index=True, default='APPROVED', help_text='Workflow status (Draft, Pending, Approved)', max_length=10),
        ),
    ]
