# Generated by Django 5.0.3 on 2026-04-19 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stockitem_last_synced_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='sync_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SYNCED', 'Synced'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='tally_id',
            field=models.CharField(blank=True, db_index=True, help_text='Matching name or ID in Tally ERP', max_length=255, null=True),
        ),
    ]
