# Generated by Django 5.0.3 on 2026-04-21 09:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('inventory', '0003_alter_stockitem_last_synced_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft-delete flag. Inactive records are hidden by default.')),
                ('name', models.CharField(max_length=255)),
                ('sync_status', models.CharField(choices=[('PENDING', 'Pending'), ('SYNCED', 'Synced'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('tally_id', models.CharField(blank=True, db_index=True, help_text='Matching name or ID in Tally ERP', max_length=255, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(help_text='The company this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who created this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent stock group for nested categories.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='inventory.stockgroup')),
                ('updated_by', models.ForeignKey(blank=True, help_text='The user who last updated this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stock Group',
                'verbose_name_plural': 'Stock Groups',
                'ordering': ['name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.AddField(
            model_name='stockitem',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Category or group this item belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='inventory.stockgroup'),
        ),
    ]
