# Generated by Django 5.0.3 on 2026-04-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_stockgroup_stockitem_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='closing_stock_qty',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Current/closing stock quantity from Tally sync.', max_digits=20),
        ),
    ]
