# Generated by Django 5.0.3 on 2026-04-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_stocktransaction_tally_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='GST rate in percentage (e.g., 18.00).', max_digits=5),
        ),
    ]
