# Generated by Django 5.0.3 on 2026-04-23 06:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('inventory', '0007_stockitem_gst_rate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockitem',
            name='gst_rate',
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='unit_of_measure',
            field=models.CharField(blank=True, help_text='Legacy text-based UoM. Use unit instead.', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft-delete flag. Inactive records are hidden by default.')),
                ('sync_status', models.CharField(choices=[('PENDING', 'Pending'), ('SYNCED', 'Synced'), ('FAILED', 'Failed')], db_index=True, default='PENDING', help_text='Status of synchronization with Tally.', max_length=20)),
                ('tally_id', models.CharField(blank=True, db_index=True, help_text='External ID mapping to the Tally record.', max_length=255, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='Timestamp of the last successful synchronization.', null=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(help_text='The company this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who created this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent godown/location.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='inventory.location')),
                ('updated_by', models.ForeignKey(blank=True, help_text='The user who last updated this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Location (Godown)',
                'verbose_name_plural': 'Locations (Godowns)',
                'ordering': ['name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Godown/Location where this transaction occurred.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='inventory.location'),
        ),
        migrations.CreateModel(
            name='StockCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft-delete flag. Inactive records are hidden by default.')),
                ('sync_status', models.CharField(choices=[('PENDING', 'Pending'), ('SYNCED', 'Synced'), ('FAILED', 'Failed')], db_index=True, default='PENDING', help_text='Status of synchronization with Tally.', max_length=20)),
                ('tally_id', models.CharField(blank=True, db_index=True, help_text='External ID mapping to the Tally record.', max_length=255, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='Timestamp of the last successful synchronization.', null=True)),
                ('name', models.CharField(max_length=255)),
                ('company', models.ForeignKey(help_text='The company this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who created this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent stock category for nested categories.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='inventory.stockcategory')),
                ('updated_by', models.ForeignKey(blank=True, help_text='The user who last updated this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stock Category',
                'verbose_name_plural': 'Stock Categories',
                'ordering': ['name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.AddField(
            model_name='stockitem',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Secondary classification (e.g., Brand).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='inventory.stockcategory'),
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft-delete flag. Inactive records are hidden by default.')),
                ('sync_status', models.CharField(choices=[('PENDING', 'Pending'), ('SYNCED', 'Synced'), ('FAILED', 'Failed')], db_index=True, default='PENDING', help_text='Status of synchronization with Tally.', max_length=20)),
                ('tally_id', models.CharField(blank=True, db_index=True, help_text='External ID mapping to the Tally record.', max_length=255, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='Timestamp of the last successful synchronization.', null=True)),
                ('symbol', models.CharField(help_text='Short name (e.g., Kgs)', max_length=20)),
                ('formal_name', models.CharField(help_text='Full name (e.g., Kilograms)', max_length=100)),
                ('decimal_places', models.PositiveSmallIntegerField(default=0, help_text='Number of decimal places allowed for quantities.')),
                ('company', models.ForeignKey(help_text='The company this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who created this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='The user who last updated this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
                'ordering': ['formal_name'],
                'unique_together': {('company', 'symbol')},
            },
        ),
        migrations.AddField(
            model_name='stockitem',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='Primary Unit of Measure.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='inventory.unit'),
        ),
    ]
