# Generated by Django 5.0.3 on 2026-04-23 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_stockitem_gst_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockcategory',
            name='alias',
            field=models.CharField(blank=True, help_text='Alternative name for the category.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stockgroup',
            name='alias',
            field=models.CharField(blank=True, help_text='Alternative name for the group.', max_length=255, null=True),
        ),
    ]
