# Generated by Django 5.2.13 on 2026-04-17 12:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft-delete flag. Inactive records are hidden by default.')),
                ('name', models.CharField(help_text='Full legal name of the company.', max_length=255, unique=True)),
                ('tax_id', models.CharField(blank=True, help_text='GSTIN/VAT or other tax identification number.', max_length=50)),
                ('address', models.TextField(blank=True, help_text='Registered office address.')),
                ('currency', models.CharField(default='INR', help_text='Base currency (e.g., INR, USD).', max_length=10)),
                ('financial_year_start', models.DateField(help_text='Start date of the current financial year.')),
                ('financial_year_end', models.DateField(help_text='End date of the current financial year.')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who created this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='The user who last updated this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
    ]
