# Generated by Django 5.2.13 on 2026-04-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last successful synchronization.', null=True),
        ),
        migrations.AddField(
            model_name='ledgergroup',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last successful synchronization.', null=True),
        ),
    ]
