# Generated by Django 5.0.3 on 2026-04-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_ledger_last_synced_at_ledgergroup_last_synced_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='tally_id',
            field=models.CharField(blank=True, db_index=True, help_text='External ID mapping to the Tally record.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ledgergroup',
            name='tally_id',
            field=models.CharField(blank=True, db_index=True, help_text='External ID mapping to the Tally record.', max_length=255, null=True),
        ),
    ]
