# Generated by Django 5.0.3 on 2026-04-23 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_ledger_credit_limit_budget_currency_scenario'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgergroup',
            name='alias',
            field=models.CharField(blank=True, help_text='Alternative name for the group.', max_length=255, null=True),
        ),
    ]
