# Generated by Django 5.0.3 on 2026-04-24 11:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('invoicing', '0001_initial'),
        ('voucher', '0007_voucherentry_gst_applicable_voucherentry_hsn_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft-delete flag. Inactive records are hidden by default.')),
                ('sync_status', models.CharField(choices=[('PENDING', 'Pending'), ('SYNCED', 'Synced'), ('FAILED', 'Failed')], db_index=True, default='PENDING', help_text='Status of synchronization with Tally.', max_length=20)),
                ('tally_id', models.CharField(blank=True, db_index=True, help_text='External ID mapping to the Tally record.', max_length=255, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='Timestamp of the last successful synchronization.', null=True)),
                ('invoice_number', models.CharField(db_index=True, help_text='Unique invoice number (e.g., INV-2026-0001)', max_length=50, unique=True)),
                ('invoice_date', models.DateField(auto_now_add=True, help_text='Date when the invoice was generated')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_gstin', models.CharField(blank=True, help_text='GSTIN of the customer', max_length=15, null=True)),
                ('billing_address', models.TextField(blank=True, help_text='Billing address of the customer at time of sale')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Base taxable amount (excluding GST)', max_digits=20)),
                ('total_tax', models.DecimalField(decimal_places=2, help_text='Aggregated GST amount', max_digits=20)),
                ('grand_total', models.DecimalField(decimal_places=2, help_text='Final invoice value (Base + Tax)', max_digits=20)),
                ('company', models.ForeignKey(help_text='The company this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who created this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='The user who last updated this record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('voucher', models.OneToOneField(help_text='The Sales Voucher this invoice is linked to.', on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='voucher.voucher')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-invoice_date', '-invoice_number'],
            },
        ),
        migrations.DeleteModel(
            name='InvoiceMetadata',
        ),
    ]
